name: Extract release notes
description: Extracts release notes from pull requests
inputs:
  releaseNotesPath:
    description: Path where release notes will be stored
    required: false
outputs:
  releaseNotesPath:
    description: Path where release notes were stored, if successful
runs:
  using: docker
  image: Dockerfile
branding:
  icon: download
  color: blue
