name: extract-release-notes
description: Extracts release notes from pull requests
inputs:
  releaseNotesPath:
    description: Path to store the release notes in
    default: $GITHUB_WORKSPACE/__RELEASE_NOTES.md
outputs:
  releaseNotesPath:
    description: Path the release notes were stored in
runs:
  using: 'node12'
  main: 'dist/index.js'
