name: extract-release-notes
description: Extracts release notes from pull requests
inputs:
  fromFile:
    description: Read the pull request body from this file instead of the event JSON
  releaseNotesPath:
    description: Path to store the release notes in
    default: ${{ github.workspace }}/__RELEASE_NOTES.md
outputs:
  releaseNotesPath:
    description: Path the release notes were stored in
runs:
  using: 'node12'
  main: 'dist/index.js'
