name: Test
on:
  pull_request:
  push:
    branches:
      - primary

jobs:
  unitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run ci
  integrationTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        id: result
        with:
          fromFile: "$GITHUB_WORKSPACE/test/fixtures/test-release-notes.md"

      - run: diff "$GITHUB_WORKSPACE/test/fixtures/result-release-notes.md" "$GITHUB_WORKSPACE/__RELEASE_NOTES.md"
